version: '2'

services:
  db:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - db-data:/var/lib/mysql
      - ./db/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    env_file: .env

  wordpress:
    image: wordpress:latest
    container_name: wp
    depends_on:
      - db
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./wp:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
    links:
      - db
    ports:
      - 18080:80
    volumes:
      - /sessions

volumes:
  db-data:
    driver: local
