version: '2'

services:
  db:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - db_data:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wp
    depends_on:
      - db
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db:3306
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  db_data:
